/*
 * Copyright (C) 2015 Dipu
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ClientApplication;

import Utilities.Functions;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dipu
 */
public class OverviewForm extends javax.swing.JFrame
{
    //parent form to this form
    private final ServerLink mServerLink;

    /**
     * Creates new OverviewForm.
     *
     * @param serverLink ServerLink object to connect with server
     */
    public OverviewForm(ServerLink serverLink)
    {
        mServerLink = serverLink;

        initComponents();
        loadPropertyTable();

        this.toFront();
        this.requestFocus();
        this.requestFocusInWindow();
    }

    private void loadPropertyTable()
    {
        long start = mServerLink.getStartTime();
        long stop = mServerLink.getStopTime();
        long offset = mServerLink.getServerTime() - System.currentTimeMillis();
        String server = mServerLink.getServerIP() + ":" + mServerLink.getPort();

        DefaultTableModel model = (DefaultTableModel) propertyTable.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        model.addRow(new Object[]{"Server", server});
        model.addRow(new Object[]{"Title", mServerLink.getExamTitle()});
        model.addRow(new Object[]{"Registration No", mServerLink.getRegistrationNo()});
        model.addRow(new Object[]{"Candidate Name", mServerLink.getCandidateName()});
        model.addRow(new Object[]{"Start Time", new Date(start + offset)});
        model.addRow(new Object[]{"End Time", new Date(stop + offset)});
        model.addRow(new Object[]{"Duration", Functions.formatTimeSpan(stop - start)});
        model.addRow(new Object[]{"Login Attempts", mServerLink.getLoginAttempts()});
        model.addRow(new Object[]{"Question Count", mServerLink.getQuestionCount()});
        model.addRow(new Object[]{"Total Marks", mServerLink.getTotalMarks()});
        model.addRow(new Object[]{"Total Submissions", mServerLink.getTotalSubmission()});
        model.addRow(new Object[]{"Submitted Questions", mServerLink.getSubmittedQuestionCount()});
        model.addRow(new Object[]{"Submitted Marks", mServerLink.getSubmittedMarks()});
        //ips that has been used by this candidate        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        titleBar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        propertyTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exam Overview");

        titleBar.setBackground(new java.awt.Color(79, 129, 179));
        titleBar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        titleBar.setForeground(new java.awt.Color(255, 230, 172));
        titleBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleBar.setText("Exam is over.");
        titleBar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 2, new java.awt.Color(153, 153, 0)));
        titleBar.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(161, 143, 198));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exam overview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(204, 255, 255)));

        propertyTable.setBackground(new java.awt.Color(250, 245, 255));
        propertyTable.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        propertyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "Property", "Value"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        propertyTable.setDoubleBuffered(true);
        propertyTable.setFillsViewportHeight(true);
        propertyTable.setGridColor(new java.awt.Color(0, 204, 204));
        propertyTable.setRowHeight(18);
        propertyTable.setRowSelectionAllowed(false);
        propertyTable.setSelectionBackground(new java.awt.Color(142, 119, 205));
        propertyTable.setSelectionForeground(new java.awt.Color(255, 255, 230));
        propertyTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        propertyTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(propertyTable);
        if (propertyTable.getColumnModel().getColumnCount() > 0)
        {
            propertyTable.getColumnModel().getColumn(0).setPreferredWidth(150);
            propertyTable.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(113, 125, 165));

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit.png"))); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitButtonActionPerformed
    {//GEN-HEADEREND:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable propertyTable;
    private javax.swing.JLabel titleBar;
    // End of variables declaration//GEN-END:variables
}
